### ISSUE TITLE
Update SVGO to fix deprecation dependency warning

### ISSUE THREAD

**Issue by felixranesberger** [vbenjs/vite-plugin-svg-icons#84]
On installation of this package, a warning occurs. 
This should be fixable by updating SVGO to a newer version, since the deprecated dependency `stable` seems 
updated to a newer version in SVGO v3.

<img width="1420" alt="Screenshot 2023-02-04 at 18 40 04" src="https://user-images.githubusercontent.com/52704891/216781674-6f15098a-7fd2-4e65-936b-b93e26d25ac4.png">

<img width="840" alt="Screenshot 2023-02-04 at 18 40 16" src="https://user-images.githubusercontent.com/52704891/216781673-dde3e3e2-fd94-4f49-87b4-871147dd7213.png">

**Comment by jonkab** [comment]
Hello,
I have a similar problem.
Has anyone resolved the problem?
Thanks in advance.

![image](https://github.com/vbenjs/vite-plugin-svg-icons/assets/17063913/67cd6e87-412e-4882-8582-c2bc7914b9c1)

**Comment by felixranesberger** [comment]
You could try using `overrides` to update `svgo` internally yourself. 
Could look something like this:

```json
"overrides": {
    "vite-plugin-svg-icons": {
      "svgo": "~3.0.0"
    }
  }
```

Haven't tried or tested it though.
If this works for you, it would be awesome if you could give me some feedback with your current implementation of the fix,
because I'm also facing the issue currently :)

**Comment by jonkab** [comment]
Thank you 🙏 for your suggestion!
But unfortunately 😞 that doesn't seem to work either.

**Code package.json**
```json
{
  "name": "vite-starter",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^5.2.10"
  },
  "dependencies": {
    "vite-plugin-svg-icons": "^2.0.1"
  },
  "overrides": {
    "vite-plugin-svg-icons": {
      "svgo": "~3.0.0"
    }
  }
}
```

**obtained result** 
![image](https://github.com/vbenjs/vite-plugin-svg-icons/assets/17063913/5f49fe29-9d57-4025-b02c-04ac64e64183)

**Comment by felixranesberger** [comment]
This could work: 

```json
"overrides": {
    "svg-baker": {
      "micromatch": "^4.0.0"
    }
  }
  ```
  
  (svgo wasn't the problem but a sub-sub-dependency of svg-baker)

**Comment by jonkab** [comment]
Well done ! Indeed ! 👍
But there is still the **stable@0.1.8** library which is causing problems now.🤔

**package.json**
```json
{
  "name": "vite-starter",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^5.2.10"
  },
  "dependencies": {
    "vite-plugin-svg-icons": "^2.0.1"
  },
  "overrides": {
    "svg-baker": {
      "micromatch": "^4.0.0"
    }
  }
}
```

**Screenshot**
![image](https://github.com/vbenjs/vite-plugin-svg-icons/assets/17063913/141ac8d2-b80c-45d4-be4b-e596ea1792ba)

**Comment by felixranesberger** [comment]
This should fix it

```json
"overrides": {
    "svg-baker": {
      "micromatch": "^4.0.0"
    },
    "vite-plugin-svg-icons": {
      "svgo": "^3.2.0"
    }
  }
  ```

**Comment by jonkab** [comment]
It's still the same error, I don't know why.

**package.json**
```json
{
  "name": "vite-starter",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^5.2.10"
  },
  "dependencies": {
    "vite-plugin-svg-icons": "^2.0.1"
  },
  "overrides": {
    "svg-baker": {
      "micromatch": "^4.0.0"
    },
    "vite-plugin-svg-icons": {
      "svgo": "^3.2.0"
    }
  }
}
```

**Screenshot**
![image](https://github.com/vbenjs/vite-plugin-svg-icons/assets/17063913/33335574-3e67-4f6e-aff9-7999232ab82d)

**Comment by felixranesberger** [comment]
Weird, did you try removing the `node_modules` and running `npm install` again?
I tried it on my project and I don't get the warning. 
Haven't tried if it works yet though.

**Comment by felixranesberger** [comment]
Could you resolve your error?

**Comment by yangxu52** [comment]
> Could you resolve your error?

@jonkab @felixranesberger 

You can try the maintaining version by me: [vite-plugin-svg-icons-ng](https://github.com/yangxu52/vite-plugin-svg-icons-ng).
